### ISSUE TITLE
[BUG] Profile Naming in file list

### ISSUE THREAD

**Issue by Falcon911** [Foxlider/FASTER#19]
**Describe the bug**
Update some profile settings (Player amounts or password changes) and noticed that the profile naming in the server list in the Windows File Explore is now a long sequence of words and numbers vs the name of the itself. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Server Profile  
2. Rename the Profile
3. Click on Save 
4. In file explorer, goto the Servers list and find the newly named folder
5. Only finding _4a6a746676d3481aae9a9e6948088d95 now in the time stamp for the exact time I saved it.  

**Screenshots**
https://i.imgur.com/n7hx9Kq.png

https://i.imgur.com/r1PyWjD.png

**OS Version (required):**
 - OS: windows 2012
 - Version 1.7A H1
 - 
**Additional context**
Updated to a new version of .Net, not sure if that created the issue due to I am running another tool for Dead Matter
https://github.com/winglessraven/DeadMatterServerManager/releases

**Comment by MildlyInterested** [comment]
That is how it's supposed to be since the update to 1.7. 
If you need to know which folder belongs to which profile you can right click on the profile and select "go to folder".

**Comment by Foxlider** [comment]
As @MildlyInterested said, it's standard procedure since 1.7. Reason is the following : 
Renaming a profile before was a tedious process that caused a LOT of issues. Cloning too. 
When a profile was created (ex: profile a) then a serie of folders and files would be created (a_config.cfg, a.Arma3Profile, ...)
Thyen you would rename the profile to b. but files could not change names (because some savefiles would store the profile name in the vars and things would be catastrophic) 
So you'd end up with a profile named b but all the files would remain named a
Some people would try to rename them and fail miserably as Arma would not understand stuff anymore. 

Now, profiles have an unique ID (you can see it by hovering the profile's name at the bottom of the profile view) and each file keeps this ID for identification. Then a profile have a name, given by the manager to identify in a more readable way.

**Comment by Falcon911** [comment]
Forgive me ignorance.  Could it be that the spaces would seen as %20 format and filenaming should have _ between spaces? I think the original dev of the FAST2  mention that before. Either way I get your point.
