### ISSUE TITLE
[BUG] No mods can be updated

### ISSUE THREAD

**Issue by PreAmbience** [Foxlider/FASTER#64]
**Describe the bug**
First installation of all my current mods have worked without a hitch but updating seems not to work.
The tool checks for updates properly but when I choose to update any of them, the updater shows the following:

Fetching mod ID infos... 
Attempting to start download of item ID... 
OK.
Downloading X files with total size of    X,XX  B...
Progress 00,00%
Error: The process cannot access the file 'C:\Users\Server\Documents\ModStagingDirectory\ID\addons\file.pbo' because it is being used by another process.

- Everything else seems to work fine. Installing new mods, deploying, running the servers and headless clients.
- It is the same no matter what mod I try to update.
- Same result whether I do an automatic update on all mods or attempt to update them one by one.
- There is no other process except FASTER running that can possibly be using the file. Even after a clean reboot, the problem remains.
- FASTER runs as administrator.
- I have tried turning all anti-virus and similar off.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Mods.
2. Click to update any mod.
3. Error occurs and no mod files are downloaded.

**OS and Software**
 - OS: Windows 10 Pro 20H2, 19042.1526
 - Software: FASTER 1.8b (latest)

**Comment by Foxlider** [comment]
Known bug due to an outdated version of the updater

You can use the following link to download the test version : 
[FASTER 1.8 BETA](https://install.appcenter.ms/users/keelah/apps/faster-1/distribution_groups/public/releases/6)

Here is the changelog you gotta read :

![image](https://user-images.githubusercontent.com/19773387/155767092-c9bda047-8785-4042-9f62-4b50987cf537.png)
![image](https://user-images.githubusercontent.com/19773387/155767116-2e2c6e4d-3634-4cce-9cfd-92e7f5ffdd08.png)
![image](https://user-images.githubusercontent.com/19773387/155767138-93ea00ae-d7af-4285-bae6-c4fd2776fde8.png)
